source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.baijiahulian.com/app/specs.git'
# source 'https://github.com/baijia/specs.git'

# platform :ios, ‘7.0’
# inhibit_all_warnings!

target 'BJPlaybackCore_Example' do
  pod 'BJPlaybackCore', :path => '../'
end
