source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/baijia/specs.git'

# platform :ios, ‘7.0’
# inhibit_all_warnings!

target 'BJPlaybackCore_Example' do

  pod ‘BJPlaybackCore’
  pod 'BJHL-Kit-iOS'
  pod 'Masonry'
  pod ‘ReactiveCocoa’, ‘~>2.0’
  pod ‘SDWebImage’
  
end
 